// Code generated by ent, DO NOT EDIT.

package episode

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the episode type in the database.
	Label = "episode"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldThumbnail holds the string denoting the thumbnail field in the database.
	FieldThumbnail = "thumbnail"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldComicID holds the string denoting the comic_id field in the database.
	FieldComicID = "comic_id"
	// EdgeComic holds the string denoting the comic edge name in mutations.
	EdgeComic = "comic"
	// Table holds the table name of the episode in the database.
	Table = "episodes"
	// ComicTable is the table that holds the comic relation/edge.
	ComicTable = "episodes"
	// ComicInverseTable is the table name for the Comic entity.
	// It exists in this package in order to avoid circular dependency with the "comic" package.
	ComicInverseTable = "comics"
	// ComicColumn is the table column denoting the comic relation/edge.
	ComicColumn = "comic_id"
)

// Columns holds all SQL columns for episode fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldURL,
	FieldThumbnail,
	FieldUpdatedAt,
	FieldComicID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// ThumbnailValidator is a validator for the "thumbnail" field. It is called by the builders before save.
	ThumbnailValidator func(string) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
