// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/ts1106/favomic-api/ent/comic"
	"github.com/ts1106/favomic-api/ent/magazine"
)

// MagazineCreate is the builder for creating a Magazine entity.
type MagazineCreate struct {
	config
	mutation *MagazineMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (mc *MagazineCreate) SetName(s string) *MagazineCreate {
	mc.mutation.SetName(s)
	return mc
}

// SetID sets the "id" field.
func (mc *MagazineCreate) SetID(u uuid.UUID) *MagazineCreate {
	mc.mutation.SetID(u)
	return mc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mc *MagazineCreate) SetNillableID(u *uuid.UUID) *MagazineCreate {
	if u != nil {
		mc.SetID(*u)
	}
	return mc
}

// AddComicIDs adds the "comics" edge to the Comic entity by IDs.
func (mc *MagazineCreate) AddComicIDs(ids ...uuid.UUID) *MagazineCreate {
	mc.mutation.AddComicIDs(ids...)
	return mc
}

// AddComics adds the "comics" edges to the Comic entity.
func (mc *MagazineCreate) AddComics(c ...*Comic) *MagazineCreate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return mc.AddComicIDs(ids...)
}

// Mutation returns the MagazineMutation object of the builder.
func (mc *MagazineCreate) Mutation() *MagazineMutation {
	return mc.mutation
}

// Save creates the Magazine in the database.
func (mc *MagazineCreate) Save(ctx context.Context) (*Magazine, error) {
	var (
		err  error
		node *Magazine
	)
	mc.defaults()
	if len(mc.hooks) == 0 {
		if err = mc.check(); err != nil {
			return nil, err
		}
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MagazineMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mc.check(); err != nil {
				return nil, err
			}
			mc.mutation = mutation
			if node, err = mc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			if mc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, mc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Magazine)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from MagazineMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MagazineCreate) SaveX(ctx context.Context) *Magazine {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MagazineCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MagazineCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MagazineCreate) defaults() {
	if _, ok := mc.mutation.ID(); !ok {
		v := magazine.DefaultID()
		mc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MagazineCreate) check() error {
	if _, ok := mc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Magazine.name"`)}
	}
	if v, ok := mc.mutation.Name(); ok {
		if err := magazine.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Magazine.name": %w`, err)}
		}
	}
	return nil
}

func (mc *MagazineCreate) sqlSave(ctx context.Context) (*Magazine, error) {
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (mc *MagazineCreate) createSpec() (*Magazine, *sqlgraph.CreateSpec) {
	var (
		_node = &Magazine{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: magazine.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: magazine.FieldID,
			},
		}
	)
	_spec.OnConflict = mc.conflict
	if id, ok := mc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mc.mutation.Name(); ok {
		_spec.SetField(magazine.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := mc.mutation.ComicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   magazine.ComicsTable,
			Columns: []string{magazine.ComicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: comic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Magazine.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MagazineUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (mc *MagazineCreate) OnConflict(opts ...sql.ConflictOption) *MagazineUpsertOne {
	mc.conflict = opts
	return &MagazineUpsertOne{
		create: mc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Magazine.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mc *MagazineCreate) OnConflictColumns(columns ...string) *MagazineUpsertOne {
	mc.conflict = append(mc.conflict, sql.ConflictColumns(columns...))
	return &MagazineUpsertOne{
		create: mc,
	}
}

type (
	// MagazineUpsertOne is the builder for "upsert"-ing
	//  one Magazine node.
	MagazineUpsertOne struct {
		create *MagazineCreate
	}

	// MagazineUpsert is the "OnConflict" setter.
	MagazineUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *MagazineUpsert) SetName(v string) *MagazineUpsert {
	u.Set(magazine.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MagazineUpsert) UpdateName() *MagazineUpsert {
	u.SetExcluded(magazine.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Magazine.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(magazine.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MagazineUpsertOne) UpdateNewValues() *MagazineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(magazine.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Magazine.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MagazineUpsertOne) Ignore() *MagazineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MagazineUpsertOne) DoNothing() *MagazineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MagazineCreate.OnConflict
// documentation for more info.
func (u *MagazineUpsertOne) Update(set func(*MagazineUpsert)) *MagazineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MagazineUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *MagazineUpsertOne) SetName(v string) *MagazineUpsertOne {
	return u.Update(func(s *MagazineUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MagazineUpsertOne) UpdateName() *MagazineUpsertOne {
	return u.Update(func(s *MagazineUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *MagazineUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MagazineCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MagazineUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MagazineUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MagazineUpsertOne.ID is not supported by MySQL driver. Use MagazineUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MagazineUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MagazineCreateBulk is the builder for creating many Magazine entities in bulk.
type MagazineCreateBulk struct {
	config
	builders []*MagazineCreate
	conflict []sql.ConflictOption
}

// Save creates the Magazine entities in the database.
func (mcb *MagazineCreateBulk) Save(ctx context.Context) ([]*Magazine, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Magazine, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MagazineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MagazineCreateBulk) SaveX(ctx context.Context) []*Magazine {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MagazineCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MagazineCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Magazine.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MagazineUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (mcb *MagazineCreateBulk) OnConflict(opts ...sql.ConflictOption) *MagazineUpsertBulk {
	mcb.conflict = opts
	return &MagazineUpsertBulk{
		create: mcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Magazine.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mcb *MagazineCreateBulk) OnConflictColumns(columns ...string) *MagazineUpsertBulk {
	mcb.conflict = append(mcb.conflict, sql.ConflictColumns(columns...))
	return &MagazineUpsertBulk{
		create: mcb,
	}
}

// MagazineUpsertBulk is the builder for "upsert"-ing
// a bulk of Magazine nodes.
type MagazineUpsertBulk struct {
	create *MagazineCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Magazine.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(magazine.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MagazineUpsertBulk) UpdateNewValues() *MagazineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(magazine.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Magazine.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MagazineUpsertBulk) Ignore() *MagazineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MagazineUpsertBulk) DoNothing() *MagazineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MagazineCreateBulk.OnConflict
// documentation for more info.
func (u *MagazineUpsertBulk) Update(set func(*MagazineUpsert)) *MagazineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MagazineUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *MagazineUpsertBulk) SetName(v string) *MagazineUpsertBulk {
	return u.Update(func(s *MagazineUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MagazineUpsertBulk) UpdateName() *MagazineUpsertBulk {
	return u.Update(func(s *MagazineUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *MagazineUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MagazineCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MagazineCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MagazineUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
