// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Author is the predicate function for author builders.
type Author func(*sql.Selector)

// Comic is the predicate function for comic builders.
type Comic func(*sql.Selector)

// Episode is the predicate function for episode builders.
type Episode func(*sql.Selector)

// Magazine is the predicate function for magazine builders.
type Magazine func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
